# bestLogger - Логгер действий игроков
# Разработано командой разработчиков: https://vk.com/beststudio_ru
#
# Данный плагин скачивается исключительно с официального источника - ВКонтакте
# Он полностью бесплатен и также имеет открытый исходный код ()
# Что позволяет Вам быть уверенным, что Ваш сервер в безопасности.
#
# Спасибо за использование наших ресурсов!
#
#=-=-=#=-=-=#=-=-=#=-=-=#=-=-=#=-=-=#=-=-=#=-=-=#=-=-=#=-=-=#=-=-=#=-=-=#=-=-=#=-=-=#=-=-=#