# bestLogger - Логгер действий игроков
# Разработано командой разработчиков: https://vk.com/beststudio_ru
#
# Данный плагин скачивается исключительно с официального источника - ВКонтакте или компилируется самостоятельно из исходников на GitHub'е
# Он полностью бесплатен и также имеет открытый исходный код (https://github.com/lxckscream/bestLogger)
# Что позволяет Вам быть уверенным, что Ваш сервер в безопасности.
#
# Спасибо за использование наших ресурсов!
#
#=-=-=#=-=-=#=-=-=#=-=-=#=-=-=#=-=-=#=-=-=#=-=-=#=-=-=#=-=-=#=-=-=#=-=-=#=-=-=#=-=-=#=-=-=#

# Лист из ников игроков, которые НЕ будут прослушиваться
ignored:
  - "lxckScream"

# Лист из слушателей, которые будут зарегистрированы при запуске плагина.
# Полный список слушателей будет сразу, при первом запуске плагина.
logging:
  - "PLAYER_JOIN_EVENT" # Заход на сервер
  - "PLAYER_QUIT_EVENT" # Выход с сервера
  - "PLAYER_CLOSE_INVENTORY" # Закрытие какого-либо инвентаря
  - "PLAYER_CHAT_EVENT" # Сообщение в чат
  - "PLAYER_COMMAND_EVENT" # Использование команды
